PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS User (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  passwordHash TEXT,
  role TEXT NOT NULL DEFAULT 'author',
  active INTEGER NOT NULL DEFAULT 1,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Category (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  parentId TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (parentId) REFERENCES Category(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Tag (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Post (
  id TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  coverImage TEXT,
  seoTitle TEXT,
  metaDescription TEXT,
  publishedAt TEXT,
  categoryId TEXT,
  authorId TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE SET NULL,
  FOREIGN KEY (authorId) REFERENCES User(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PostTag (
  postId TEXT NOT NULL,
  tagId TEXT NOT NULL,
  PRIMARY KEY (postId, tagId),
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (tagId) REFERENCES Tag(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Page (
  id TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  seoTitle TEXT,
  metaDescription TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Media (
  id TEXT PRIMARY KEY NOT NULL,
  url TEXT NOT NULL,
  altText TEXT,
  type TEXT NOT NULL,
  size INTEGER,
  uploadedBy TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ContactMessage (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new',
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PageView (
  id TEXT PRIMARY KEY NOT NULL,
  path TEXT NOT NULL,
  postId TEXT,
  referrer TEXT,
  userAgent TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS PageView_postId_idx ON PageView(postId);
CREATE INDEX IF NOT EXISTS PageView_createdAt_idx ON PageView(createdAt);

CREATE TABLE IF NOT EXISTS AuditLog (
  id TEXT PRIMARY KEY NOT NULL,
  actorId TEXT,
  actorEmail TEXT,
  action TEXT NOT NULL,
  entityType TEXT NOT NULL,
  entityId TEXT,
  summary TEXT NOT NULL,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS AuditLog_createdAt_idx ON AuditLog(createdAt);
CREATE INDEX IF NOT EXISTS AuditLog_action_idx ON AuditLog(action);
CREATE INDEX IF NOT EXISTS AuditLog_entityType_idx ON AuditLog(entityType);

CREATE TABLE IF NOT EXISTS Setting (
  key TEXT PRIMARY KEY NOT NULL,
  valueJson TEXT NOT NULL,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AiWorkflow (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  promptConfig TEXT NOT NULL,
  autoPublish INTEGER NOT NULL DEFAULT 0,
  scheduleRule TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AiJob (
  id TEXT PRIMARY KEY NOT NULL,
  workflowId TEXT,
  topic TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  inputJson TEXT,
  outputJson TEXT,
  errorLog TEXT,
  postId TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (workflowId) REFERENCES AiWorkflow(id) ON DELETE SET NULL,
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PostRevision (
  id TEXT PRIMARY KEY NOT NULL,
  postId TEXT NOT NULL,
  contentSnapshot TEXT NOT NULL,
  editorId TEXT,
  createdAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS Post_status_idx ON Post(status);
CREATE INDEX IF NOT EXISTS Post_publishedAt_idx ON Post(publishedAt);
CREATE INDEX IF NOT EXISTS Post_categoryId_idx ON Post(categoryId);
CREATE INDEX IF NOT EXISTS AiJob_status_idx ON AiJob(status);
